#!/bin/bash
set -e

SERVER="pg_db"
PW=$POSTGRES_PW
DB="levi_chat"
DB_USER="levi"

echo "echo stop & remove old docker [$SERVER] and starting new fresh instance of [$SERVER]"
(docker kill $SERVER || :) && \
  (docker rm $SERVER || :) && \
  docker run --name $SERVER -e POSTGRES_PASSWORD=$PW \
  -e PGPASSWORD=$PW \
  -p 5432:5432 \
  -d postgres:11

# wait for pg to start
echo "sleep wait for pg-server [$SERVER] to start";
sleep 3;

#create db
echo "CREATE EXTENSION IF NOT EXISTS \"pgcrypto\";" | docker exec -i $SERVER psql -U postgres;
echo "CREATE DATABASE $DB ENCODING 'UTF-8';" | docker exec -i $SERVER psql -U postgres
echo "create user $DB_USER with encrypted password '$PW' SUPERUSER;" | docker exec -i $SERVER psql -U postgres
echo "grant all privileges on database $DB to $DB_USER;" | docker exec -i $SERVER psql -U postgres
echo "\l" | docker exec -i $SERVER psql -U postgres
